/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function C_Tree_01(props) {
  const { nodes, materials } = useGLTF('/C_tree/C_Tree_01.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <group position={[0, 0, 0.02]}>
          <mesh geometry={nodes['Christmas_Tree-Black'].geometry} material={materials.Black} />
          <mesh geometry={nodes['Christmas_Tree-Light_Bulb_Emission'].geometry} material={materials['Light Bulb_Emission']} />
          <mesh geometry={nodes['Christmas_Tree-Golden_Metallic'].geometry} material={materials.Golden_Metallic} />
          <mesh geometry={nodes['Christmas_Tree-Red_Metallic'].geometry} material={materials.Red_Metallic} />
          <mesh geometry={nodes['Christmas_Tree-Material_003'].geometry} material={materials['Material 003']} />
          <mesh geometry={nodes['Christmas_Tree-Pine_Tree'].geometry} material={materials['Pine Tree']} />
          <mesh geometry={nodes['Christmas_Tree-Brown'].geometry} material={materials.Brown} />
        </group>
        <group position={[0, 0, -0.02]}>
          <mesh geometry={nodes['Present-Brown'].geometry} material={materials.Brown} />
          <mesh geometry={nodes['Present-Red_Metallic'].geometry} material={materials.Red_Metallic} />
          <mesh geometry={nodes['Present-Green'].geometry} material={materials.Green} />
          <mesh geometry={nodes['Present-White'].geometry} material={materials.White} />
          <mesh geometry={nodes['Present-Red'].geometry} material={materials.Red} />
          <mesh geometry={nodes['Present-Golden_Metallic'].geometry} material={materials.Golden_Metallic} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/C_tree/C_Tree_01.glb')
