/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function C_Tree_05(props) {
  const { nodes, materials } = useGLTF('/C_tree/C_Tree_05.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Christmas_Tree_2.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/C_tree/C_Tree_05.glb')
export default C_Tree_05
