/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Objet2_05(props) {
  const { nodes, materials } = useGLTF('/Objet2/Objet2_05.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sleight.geometry} material={materials['Mat.1']} />
    </group>
  )
}

useGLTF.preload('/Objet2/Objet2_05.glb')
export default Objet2_05