/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ArcticFox(props) {
  const { nodes, materials } = useGLTF('/Pets/arcticfox.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.ArcticFox_LOD0_1.geometry} material={materials.Mat} />
      </group>
    </group>
  )
}

useGLTF.preload('/Pets/arcticfox.glb')
