/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Pets_05(props) {
  const { nodes, materials } = useGLTF('/Pets/reindeer.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={110}>
        <mesh geometry={nodes.Reindeer_LOD0_1.geometry} material={materials['Mat.4']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Pets/reindeer.glb')
export default Pets_05
