/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Pets_04(props) {
  const { nodes, materials } = useGLTF('/Pets/polarbear.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.PolarBear_LOD0_1.geometry} material={materials['Mat.3']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Pets/polarbear.glb')
export default Pets_04
