/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Pets_08(props) {
  const { nodes, materials } = useGLTF('/Pets/snowweasel.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.SnowWeasel_LOD0_1.geometry} material={materials['Mat.7']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Pets/snowweasel.glb')
export default Pets_08
