/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Snowowl(props) {
  const { nodes, materials } = useGLTF('/Pets/snowowl.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.SnowOwl_LOD0_1.geometry} material={materials['Mat.6']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Pets/snowowl.glb')
