/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Walrus(props) {
  const { nodes, materials } = useGLTF('/Pets/walrus.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={110.8}>
        <mesh geometry={nodes.Walrus_LOD0_1.geometry} material={materials['Mat.8']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Pets/walrus.glb')
