/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Objet1_01(props) {
  const { nodes, materials } = useGLTF('/Objet1/Objet1_01.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Christmas_ball_5.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/Objet1/Objet1_01.glb')
export default Objet1_01
