/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations, Sparkles } from '@react-three/drei'
import * as THREE from "three"
export function Snowglobe(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/SnowGlobe.glb')
  const { actions } = useAnimations(animations, group)
  const Glass = {
    metalness: 1,
    roughness: .05,
    envMapIntensity: 1,
    clearcoat: 1,
    transparent: true,
    // transmission: .95,
    opacity: .5,
    reflectivity: 0,
    refractionRatio: 0.985,
    ior: 1.2,
    side: THREE.BackSide,

  }

  useEffect(() => {
    actions.animation_0.play()
  });
  return (
    <group ref={group} {...props} dispose={null} rotation={[0,360,0]}>
      <group>
        <group name="Null">
          <group name="Group001" position={[-0.19, -5.61, -1.6]} rotation={[-Math.PI / 2, 0, 3.05]}>
            <mesh name="ground" geometry={nodes.ground.geometry} material={materials.terrain} position={[-0.09, 0, -18.56]} />
          </group>
          {/* <Sparkles count={100} scale={8} size={2.5} speed={0.4} color={"lightblue"} /> */}

          <mesh name="BakedParticleMesh_001" geometry={nodes.BakedParticleMesh_001.geometry} material={materials.snowfleck} position={[-6.99, -19.18, -17.02]} rotation={[-0.02, 1.13, 2.51]} />
          <mesh name="BakedParticleMesh_002" geometry={nodes.BakedParticleMesh_002.geometry} material={materials.snowfleck} position={[17.16, -5.29, 30.22]} rotation={[-0.83, 1.12, 0.51]} />
          <mesh name="BakedParticleMesh_003" geometry={nodes.BakedParticleMesh_003.geometry} material={materials.snowfleck} position={[-3.91, -19.02, 14.78]} rotation={[-2.04, -0.3, 0.92]} />
          <mesh name="BakedParticleMesh_004" geometry={nodes.BakedParticleMesh_004.geometry} material={materials.snowfleck} position={[12.15, -12.08, -2.44]} rotation={[-2.88, 0.83, -0.81]} />
          <mesh name="BakedParticleMesh_005" geometry={nodes.BakedParticleMesh_005.geometry} material={materials.snowfleck} position={[9.71, 22.95, 8.87]} rotation={[-0.48, -0.76, 0.23]} />
          <mesh name="BakedParticleMesh_006" geometry={nodes.BakedParticleMesh_006.geometry} material={materials.snowfleck} position={[-4.34, -19.18, -4.71]} rotation={[-2.08, 0.25, 1.9]} />
          <mesh name="BakedParticleMesh_007" geometry={nodes.BakedParticleMesh_007.geometry} material={materials.snowfleck} position={[-27.65, -3.33, 11.69]} rotation={[-0.05, 0.21, 0.75]} />
          <mesh name="BakedParticleMesh_008" geometry={nodes.BakedParticleMesh_008.geometry} material={materials.snowfleck} position={[31.37, -4.58, -20.85]} rotation={[-1.52, 0.99, -1.77]} />
          <mesh name="BakedParticleMesh_009" geometry={nodes.BakedParticleMesh_009.geometry} material={materials.snowfleck} position={[0.12, -18.87, -39.72]} rotation={[1.27, -0.15, -0.53]} />
          <mesh name="BakedParticleMesh_010" geometry={nodes.BakedParticleMesh_010.geometry} material={materials.snowfleck} position={[-36.74, -14.06, -4.2]} rotation={[-1.37, 0.91, -0.69]} />
          <mesh name="BakedParticleMesh_011" geometry={nodes.BakedParticleMesh_011.geometry} material={materials.snowfleck} position={[20.1, -19.18, -2.03]} rotation={[3.06, -0.84, -0.64]} />
          <mesh name="BakedParticleMesh_012" geometry={nodes.BakedParticleMesh_012.geometry} material={materials.snowfleck} position={[-11.77, -19.19, 9.41]} rotation={[-2.68, -0.59, 2.28]} />
          <mesh name="BakedParticleMesh_013" geometry={nodes.BakedParticleMesh_013.geometry} material={materials.snowfleck} position={[15.35, -19.18, -4.09]} rotation={[-1.41, 0.95, -1.24]} />
          <mesh name="BakedParticleMesh_014" geometry={nodes.BakedParticleMesh_014.geometry} material={materials.snowfleck} position={[4.48, -12.68, -31.39]} rotation={[1.99, -0.57, 1.97]} />
          <mesh name="BakedParticleMesh_015" geometry={nodes.BakedParticleMesh_015.geometry} material={materials.snowfleck} position={[-13.92, -14.08, 32.66]} rotation={[-3.07, 0.42, 1.69]} />
          <mesh name="BakedParticleMesh_016" geometry={nodes.BakedParticleMesh_016.geometry} material={materials.snowfleck} position={[-14.44, 10.79, 31.94]} rotation={[2.04, 0.42, 2.11]} />
          <mesh name="BakedParticleMesh_017" geometry={nodes.BakedParticleMesh_017.geometry} material={materials.snowfleck} position={[-42.64, -0.36, -18.82]} rotation={[-0.01, 0.81, 2.05]} />
          <mesh name="BakedParticleMesh_018" geometry={nodes.BakedParticleMesh_018.geometry} material={materials.snowfleck} position={[-19.75, -18.57, -38.92]} rotation={[-2.73, -0.06, 1.3]} />
          <mesh name="BakedParticleMesh_019" geometry={nodes.BakedParticleMesh_019.geometry} material={materials.snowfleck} position={[-3.19, -3.03, -44.04]} rotation={[-2.05, 0.7, 2.66]} />
          <mesh name="BakedParticleMesh_020" geometry={nodes.BakedParticleMesh_020.geometry} material={materials.snowfleck} position={[-4.41, -19.18, 22.38]} rotation={[-0.54, -0.38, 0.48]} />
          <mesh name="BakedParticleMesh_021" geometry={nodes.BakedParticleMesh_021.geometry} material={materials.snowfleck} position={[-6.72, -12.99, -27.91]} rotation={[0.4, 0.1, 1.52]} />
          <mesh name="BakedParticleMesh_022" geometry={nodes.BakedParticleMesh_022.geometry} material={materials.snowfleck} position={[-11.71, -7.05, -19.94]} rotation={[-0.77, -0.11, -1.12]} />
          <mesh name="BakedParticleMesh_023" geometry={nodes.BakedParticleMesh_023.geometry} material={materials.snowfleck} position={[-4.33, -11.64, -33.75]} rotation={[2.48, 0.14, -0.92]} />
          <mesh name="BakedParticleMesh_024" geometry={nodes.BakedParticleMesh_024.geometry} material={materials.snowfleck} position={[-24.48, -9.35, -38.23]} rotation={[-1.97, 0.71, -1.53]} />
          <mesh name="BakedParticleMesh_025" geometry={nodes.BakedParticleMesh_025.geometry} material={materials.snowfleck} position={[21.87, 8.34, -35.61]} rotation={[-0.91, -0.19, 1.41]} />
          <mesh name="BakedParticleMesh_026" geometry={nodes.BakedParticleMesh_026.geometry} material={materials.snowfleck} position={[-34.32, -7.09, -17.07]} rotation={[-1.4, -0.89, -1.14]} />
          <mesh name="BakedParticleMesh_027" geometry={nodes.BakedParticleMesh_027.geometry} material={materials.snowfleck} position={[25.78, 4.85, -18.85]} rotation={[-2.95, 0.61, 0.24]} />
          <mesh name="BakedParticleMesh_028" geometry={nodes.BakedParticleMesh_028.geometry} material={materials.snowfleck} position={[21.57, -9.05, 4.02]} rotation={[-0.14, 0.35, -0.65]} />
          <mesh name="BakedParticleMesh_029" geometry={nodes.BakedParticleMesh_029.geometry} material={materials.snowfleck} position={[4.55, 21.76, 32.59]} rotation={[1.8, -0.14, -1.23]} />
          <mesh name="BakedParticleMesh_030" geometry={nodes.BakedParticleMesh_030.geometry} material={materials.snowfleck} position={[27.46, -19.18, -4.82]} rotation={[2.21, 0.22, 0.71]} />
          <mesh name="BakedParticleMesh_031" geometry={nodes.BakedParticleMesh_031.geometry} material={materials.snowfleck} position={[-22.93, -6.34, 36.65]} rotation={[0.25, 1.28, -1.84]} />
          <mesh name="BakedParticleMesh_032" geometry={nodes.BakedParticleMesh_032.geometry} material={materials.snowfleck} position={[31.92, 5.63, -0.57]} rotation={[-0.24, -1.07, 1.22]} />
          <mesh name="BakedParticleMesh_033" geometry={nodes.BakedParticleMesh_033.geometry} material={materials.snowfleck} position={[27.26, -14.24, -5.81]} rotation={[3.11, -0.93, 1.04]} />
          <mesh name="BakedParticleMesh_034" geometry={nodes.BakedParticleMesh_034.geometry} material={materials.snowfleck} position={[-25.4, 16.46, -33.19]} rotation={[1.18, 0.17, -2.49]} />
          <mesh name="BakedParticleMesh_035" geometry={nodes.BakedParticleMesh_035.geometry} material={materials.snowfleck} position={[3.84, 5.87, 40.71]} rotation={[-1.35, -0.1, 2.63]} />
          <mesh name="BakedParticleMesh_036" geometry={nodes.BakedParticleMesh_036.geometry} material={materials.snowfleck} position={[-25.43, -17.72, 9.71]} rotation={[0.46, -1.21, -0.96]} />
          <mesh name="BakedParticleMesh_037" geometry={nodes.BakedParticleMesh_037.geometry} material={materials.snowfleck} position={[2.54, -15.45, -46.97]} rotation={[0.13, 0.41, -2.96]} />
          <mesh name="BakedParticleMesh_038" geometry={nodes.BakedParticleMesh_038.geometry} material={materials.snowfleck} position={[20.79, -12.93, -7.71]} rotation={[2.12, -0.61, 2.89]} />
          <mesh name="BakedParticleMesh_039" geometry={nodes.BakedParticleMesh_039.geometry} material={materials.snowfleck} position={[3.36, -19.18, 1.43]} rotation={[-2.52, -0.06, 2.58]} />
          <mesh name="BakedParticleMesh_040" geometry={nodes.BakedParticleMesh_040.geometry} material={materials.snowfleck} position={[-3.3, -19.18, -22.92]} rotation={[2.71, -0.19, -0.5]} />
          <mesh name="BakedParticleMesh_041" geometry={nodes.BakedParticleMesh_041.geometry} material={materials.snowfleck} position={[-22.26, -15.86, -5.44]} rotation={[-2.32, 0.55, -1.79]} />
          <mesh name="BakedParticleMesh_042" geometry={nodes.BakedParticleMesh_042.geometry} material={materials.snowfleck} position={[6.27, -19.07, 8.67]} rotation={[-0.15, -0.41, -0.47]} />
          <mesh name="BakedParticleMesh_043" geometry={nodes.BakedParticleMesh_043.geometry} material={materials.snowfleck} position={[-3.91, 17.71, 30.83]} rotation={[-0.64, 0.29, 3.09]} />
          <mesh name="BakedParticleMesh_044" geometry={nodes.BakedParticleMesh_044.geometry} material={materials.snowfleck} position={[-13.36, -15.13, 33.07]} rotation={[-1.41, 1.01, 2.12]} />
          <mesh name="BakedParticleMesh_045" geometry={nodes.BakedParticleMesh_045.geometry} material={materials.snowfleck} position={[23.28, -18.87, 9.05]} rotation={[1.88, -0.09, -2.22]} />
          <mesh name="BakedParticleMesh_046" geometry={nodes.BakedParticleMesh_046.geometry} material={materials.snowfleck} position={[17.72, -10.86, 37.22]} rotation={[2.53, 1.36, -1.74]} />
          <mesh name="BakedParticleMesh_047" geometry={nodes.BakedParticleMesh_047.geometry} material={materials.snowfleck} position={[-30.89, -8.94, -9.42]} rotation={[1.86, -0.14, -2.33]} />
          <mesh name="BakedParticleMesh_048" geometry={nodes.BakedParticleMesh_048.geometry} material={materials.snowfleck} position={[-13.73, -19.07, 9.61]} rotation={[-1.46, -0.84, 2.66]} />
          <mesh name="BakedParticleMesh_049" geometry={nodes.BakedParticleMesh_049.geometry} material={materials.snowfleck} position={[26.46, -4.1, -38.54]} rotation={[0.57, -0.51, 0.35]} />
          <mesh name="BakedParticleMesh_050" geometry={nodes.BakedParticleMesh_050.geometry} material={materials.snowfleck} position={[-16.54, -19.18, 1.11]} rotation={[2.77, -0.16, -2.84]} />
          <mesh name="BakedParticleMesh_051" geometry={nodes.BakedParticleMesh_051.geometry} material={materials.snowfleck} position={[-13.94, -19.18, 24.1]} rotation={[1.78, -0.35, -0.29]} />
          <mesh name="BakedParticleMesh_052" geometry={nodes.BakedParticleMesh_052.geometry} material={materials.snowfleck} position={[5.14, -4.88, 0.1]} rotation={[1.64, -0.33, -2.2]} />
          <mesh name="BakedParticleMesh_053" geometry={nodes.BakedParticleMesh_053.geometry} material={materials.snowfleck} position={[-4.38, -18.94, -40.1]} rotation={[-2.89, 0.11, -0.27]} />
          <mesh name="BakedParticleMesh_054" geometry={nodes.BakedParticleMesh_054.geometry} material={materials.snowfleck} position={[-24.92, -17.03, -17.94]} rotation={[0.17, -1.41, -2.5]} />
          <mesh name="BakedParticleMesh_055" geometry={nodes.BakedParticleMesh_055.geometry} material={materials.snowfleck} position={[-29.94, 2.25, -3.57]} rotation={[0.63, -0.57, 1.58]} />
          <mesh name="BakedParticleMesh_056" geometry={nodes.BakedParticleMesh_056.geometry} material={materials.snowfleck} position={[-5.48, -15.43, -41.67]} rotation={[-1.93, 0.85, -3.01]} />
          <mesh name="BakedParticleMesh_057" geometry={nodes.BakedParticleMesh_057.geometry} material={materials.snowfleck} position={[35.94, -19.18, -1.99]} rotation={[-0.3, 0.66, 2.61]} />
          <mesh name="BakedParticleMesh_058" geometry={nodes.BakedParticleMesh_058.geometry} material={materials.snowfleck} position={[35.33, 1.86, 26.72]} rotation={[0.22, -0.15, -0.2]} />
          <mesh name="BakedParticleMesh_059" geometry={nodes.BakedParticleMesh_059.geometry} material={materials.snowfleck} position={[-35.66, -1.48, -2.79]} rotation={[0.27, 0.07, -0.52]} />
          <mesh name="BakedParticleMesh_060" geometry={nodes.BakedParticleMesh_060.geometry} material={materials.snowfleck} position={[35.8, -12.6, 25.98]} rotation={[-1.77, 1.35, -2.16]} />
          <mesh name="BakedParticleMesh_061" geometry={nodes.BakedParticleMesh_061.geometry} material={materials.snowfleck} position={[-16.99, -11.16, 11.31]} rotation={[-0.21, 0.42, -0.47]} />
          <mesh name="BakedParticleMesh_062" geometry={nodes.BakedParticleMesh_062.geometry} material={materials.snowfleck} position={[-32.68, 5.78, 28.51]} rotation={[-1.87, 0.21, -1.82]} />
          <mesh name="BakedParticleMesh_063" geometry={nodes.BakedParticleMesh_063.geometry} material={materials.snowfleck} position={[-10.08, -5.9, 43.84]} rotation={[2.31, 1.23, -2.42]} />
          <mesh name="BakedParticleMesh_064" geometry={nodes.BakedParticleMesh_064.geometry} material={materials.snowfleck} position={[-3.83, 26.23, 26.74]} rotation={[-0.67, 0.86, 2.46]} />
          <mesh name="BakedParticleMesh_065" geometry={nodes.BakedParticleMesh_065.geometry} material={materials.snowfleck} position={[-16.71, -12.37, 13.37]} rotation={[-3.12, 0.54, 0.06]} />
          <mesh name="BakedParticleMesh_066" geometry={nodes.BakedParticleMesh_066.geometry} material={materials.snowfleck} position={[-32.14, -4.46, 30.3]} rotation={[-0.38, -0.26, 1.52]} />
          <mesh name="BakedParticleMesh_067" geometry={nodes.BakedParticleMesh_067.geometry} material={materials.snowfleck} position={[-13.72, -18.58, -19.07]} rotation={[0.62, -0.16, -1.85]} />
          <mesh name="BakedParticleMesh_068" geometry={nodes.BakedParticleMesh_068.geometry} material={materials.snowfleck} position={[32.24, -13.64, 22.2]} rotation={[1.75, 0.55, 2.85]} />
          <mesh name="BakedParticleMesh_069" geometry={nodes.BakedParticleMesh_069.geometry} material={materials.snowfleck} position={[-41.89, -17.01, -14.94]} rotation={[0.87, 1.11, -2.54]} />
          <mesh name="BakedParticleMesh_070" geometry={nodes.BakedParticleMesh_070.geometry} material={materials.snowfleck} position={[-27.28, -16.63, 2.9]} rotation={[0.92, 0.55, 2.18]} />
          <mesh name="BakedParticleMesh_071" geometry={nodes.BakedParticleMesh_071.geometry} material={materials.snowfleck} position={[17.56, -18.82, -16.13]} rotation={[1.54, 0.82, -2.39]} />
          <mesh name="BakedParticleMesh_072" geometry={nodes.BakedParticleMesh_072.geometry} material={materials.snowfleck} position={[7.76, -15.21, -31.99]} rotation={[1.4, -0.68, -0.1]} />
          <mesh name="BakedParticleMesh_073" geometry={nodes.BakedParticleMesh_073.geometry} material={materials.snowfleck} position={[-22.16, -19.18, 7.4]} rotation={[0.91, -0.65, 1.85]} />
          <mesh name="BakedParticleMesh_074" geometry={nodes.BakedParticleMesh_074.geometry} material={materials.snowfleck} position={[29.96, 3.73, 22.51]} rotation={[-0.65, -0.83, 0.05]} />
          <mesh name="BakedParticleMesh_075" geometry={nodes.BakedParticleMesh_075.geometry} material={materials.snowfleck} position={[-14.69, 16.76, -29.28]} rotation={[-3.09, -0.58, 2.56]} />
          <mesh name="BakedParticleMesh_076" geometry={nodes.BakedParticleMesh_076.geometry} material={materials.snowfleck} position={[24.49, 11.71, 6.98]} rotation={[-1.79, -0.29, 2.19]} />
          <mesh name="BakedParticleMesh_077" geometry={nodes.BakedParticleMesh_077.geometry} material={materials.snowfleck} position={[28.74, -15.17, 12.12]} rotation={[2.27, -0.23, 2.06]} />
          <mesh name="BakedParticleMesh_078" geometry={nodes.BakedParticleMesh_078.geometry} material={materials.snowfleck} position={[18.92, -4.2, -22.39]} rotation={[-1.95, -0.44, -0.99]} />
          <mesh name="BakedParticleMesh_079" geometry={nodes.BakedParticleMesh_079.geometry} material={materials.snowfleck} position={[-9.97, -2.61, -5.15]} rotation={[2.88, -0.56, -1.04]} />
          <mesh name="BakedParticleMesh_080" geometry={nodes.BakedParticleMesh_080.geometry} material={materials.snowfleck} position={[-23.01, 10.48, -17.08]} rotation={[-0.8, 0.19, 1.08]} />
          <mesh name="BakedParticleMesh_081" geometry={nodes.BakedParticleMesh_081.geometry} material={materials.snowfleck} position={[33.07, 11.12, 13.34]} rotation={[-1.93, -0.4, -2.72]} />
          <mesh name="BakedParticleMesh_082" geometry={nodes.BakedParticleMesh_082.geometry} material={materials.snowfleck} position={[2.69, -0.35, -23.72]} rotation={[-2.18, 0.73, 2.43]} />
          <mesh name="BakedParticleMesh_083" geometry={nodes.BakedParticleMesh_083.geometry} material={materials.snowfleck} position={[6.84, 15.26, 28.13]} rotation={[-0.72, 1.37, 2.43]} />
          <mesh name="BakedParticleMesh_084" geometry={nodes.BakedParticleMesh_084.geometry} material={materials.snowfleck} position={[14.89, 8.55, 2.37]} rotation={[-3.12, 0, -2.62]} />
          <mesh name="BakedParticleMesh_085" geometry={nodes.BakedParticleMesh_085.geometry} material={materials.snowfleck} position={[40.96, 13.3, -3.72]} rotation={[-1.16, 1.01, -1.5]} />
          <mesh name="BakedParticleMesh_086" geometry={nodes.BakedParticleMesh_086.geometry} material={materials.snowfleck} position={[23.44, 3.78, -15.15]} rotation={[1.72, -0.98, -2.63]} />
          <mesh name="BakedParticleMesh_087" geometry={nodes.BakedParticleMesh_087.geometry} material={materials.snowfleck} position={[-6.89, -14.14, -14.6]} rotation={[2.72, -0.39, 0]} />
          <mesh name="BakedParticleMesh_088" geometry={nodes.BakedParticleMesh_088.geometry} material={materials.snowfleck} position={[-20.9, 26.39, 12.03]} rotation={[1.25, -0.84, 2.39]} />
          <mesh name="BakedParticleMesh_089" geometry={nodes.BakedParticleMesh_089.geometry} material={materials.snowfleck} position={[-29.37, 7.08, 0.71]} rotation={[0.69, 0.3, 2.81]} />
          <mesh name="BakedParticleMesh_090" geometry={nodes.BakedParticleMesh_090.geometry} material={materials.snowfleck} position={[-29.85, -18.91, -0.16]} rotation={[-2.52, -0.21, -0.88]} />
          <mesh name="BakedParticleMesh_091" geometry={nodes.BakedParticleMesh_091.geometry} material={materials.snowfleck} position={[13.86, -3.99, 21.59]} rotation={[-0.04, -0.4, -1.84]} />
          <mesh name="BakedParticleMesh_092" geometry={nodes.BakedParticleMesh_092.geometry} material={materials.snowfleck} position={[-16.83, 20.84, 20.93]} rotation={[-1.78, -0.28, -2.85]} />
          <mesh name="BakedParticleMesh_093" geometry={nodes.BakedParticleMesh_093.geometry} material={materials.snowfleck} position={[-26.55, -12.67, -0.16]} rotation={[1.95, 0.74, -2.44]} />
          <mesh name="BakedParticleMesh_094" geometry={nodes.BakedParticleMesh_094.geometry} material={materials.snowfleck} position={[-24.55, -14.18, -4.33]} rotation={[-2.66, 0.47, -1.51]} />
          <mesh name="BakedParticleMesh_095" geometry={nodes.BakedParticleMesh_095.geometry} material={materials.snowfleck} position={[28.92, -1.86, 3.13]} rotation={[3.05, -0.04, -1.29]} />
          <mesh name="BakedParticleMesh_096" geometry={nodes.BakedParticleMesh_096.geometry} material={materials.snowfleck} position={[-0.03, 22.33, -31.78]} rotation={[-2.72, -0.61, 2.75]} />
          <mesh name="BakedParticleMesh_097" geometry={nodes.BakedParticleMesh_097.geometry} material={materials.snowfleck} position={[0.12, -15.14, 22.39]} rotation={[-0.5, 0.52, -1.16]} />
          <mesh name="BakedParticleMesh_098" geometry={nodes.BakedParticleMesh_098.geometry} material={materials.snowfleck} position={[9.37, 0.98, 23.66]} rotation={[-2.53, -0.29, -0.25]} />
          <mesh name="BakedParticleMesh_099" geometry={nodes.BakedParticleMesh_099.geometry} material={materials.snowfleck} position={[-16, -4.02, 25.73]} rotation={[2.13, -0.47, 0.15]} />
          <mesh name="BakedParticleMesh_100" geometry={nodes.BakedParticleMesh_100.geometry} material={materials.snowfleck} position={[16.1, 17.83, -21.15]} rotation={[1.13, -1.06, -0.24]} />
          <mesh name="BakedParticleMesh_101" geometry={nodes.BakedParticleMesh_101.geometry} material={materials.snowfleck} position={[1.34, -3.74, -28.7]} rotation={[1.36, -0.41, 2.28]} />
          <mesh name="BakedParticleMesh_102" geometry={nodes.BakedParticleMesh_102.geometry} material={materials.snowfleck} position={[-10.85, -19.18, -25.68]} rotation={[-2.85, -0.15, -0.38]} />
          <mesh name="BakedParticleMesh_103" geometry={nodes.BakedParticleMesh_103.geometry} material={materials.snowfleck} position={[14.2, 15.1, 20.74]} rotation={[1.44, -0.21, -0.47]} />
          <mesh name="BakedParticleMesh_104" geometry={nodes.BakedParticleMesh_104.geometry} material={materials.snowfleck} position={[11.29, 28.08, -29.06]} rotation={[1.48, 0.76, 2.04]} />
          <mesh name="BakedParticleMesh_105" geometry={nodes.BakedParticleMesh_105.geometry} material={materials.snowfleck} position={[-16.58, -19.09, -7.56]} rotation={[2.31, -1.31, -1.25]} />
          <mesh name="BakedParticleMesh_106" geometry={nodes.BakedParticleMesh_106.geometry} material={materials.snowfleck} position={[2.93, 9.12, -9.92]} rotation={[1.29, 0.42, -0.87]} />
          <mesh name="BakedParticleMesh_107" geometry={nodes.BakedParticleMesh_107.geometry} material={materials.snowfleck} position={[39.45, 10.54, 11.86]} rotation={[-1.73, 0.48, -2.31]} />
          <mesh name="BakedParticleMesh_108" geometry={nodes.BakedParticleMesh_108.geometry} material={materials.snowfleck} position={[-5.99, 0.64, 18.4]} rotation={[-0.65, 0.34, 0.83]} />
          <mesh name="BakedParticleMesh_109" geometry={nodes.BakedParticleMesh_109.geometry} material={materials.snowfleck} position={[33.29, -10.43, -32.5]} rotation={[2.69, 0.97, 0.9]} />
          <mesh name="BakedParticleMesh_110" geometry={nodes.BakedParticleMesh_110.geometry} material={materials.snowfleck} position={[36.76, 9.78, 3.7]} rotation={[-1.36, 0.6, -0.23]} />
          <mesh name="BakedParticleMesh_111" geometry={nodes.BakedParticleMesh_111.geometry} material={materials.snowfleck} position={[4.23, -19.01, -17.94]} rotation={[-2.41, -0.02, 0.08]} />
          <mesh name="BakedParticleMesh_112" geometry={nodes.BakedParticleMesh_112.geometry} material={materials.snowfleck} position={[1.94, 35.41, -6.76]} rotation={[2.89, 0.91, -1.88]} />
          <mesh name="BakedParticleMesh_113" geometry={nodes.BakedParticleMesh_113.geometry} material={materials.snowfleck} position={[5, 7.63, -39.46]} rotation={[0.8, 0.87, 0.93]} />
          <mesh name="BakedParticleMesh_114" geometry={nodes.BakedParticleMesh_114.geometry} material={materials.snowfleck} position={[-25.02, -13.41, -12.33]} rotation={[-2.3, 0.24, -0.7]} />
          <mesh name="BakedParticleMesh_115" geometry={nodes.BakedParticleMesh_115.geometry} material={materials.snowfleck} position={[27.07, -12.11, -11.07]} rotation={[0.24, 0.9, -2.58]} />
          <mesh name="BakedParticleMesh_116" geometry={nodes.BakedParticleMesh_116.geometry} material={materials.snowfleck} position={[-19.42, -18.73, -14.13]} rotation={[1.53, -0.96, 0.03]} />
          <mesh name="BakedParticleMesh_117" geometry={nodes.BakedParticleMesh_117.geometry} material={materials.snowfleck} position={[40.49, 9.94, -11.58]} rotation={[-1.19, -0.05, -2.83]} />
          <mesh name="BakedParticleMesh_118" geometry={nodes.BakedParticleMesh_118.geometry} material={materials.snowfleck} position={[-21.32, -3.55, -19.55]} rotation={[-1.51, 0.22, -1.72]} />
          <mesh name="BakedParticleMesh_119" geometry={nodes.BakedParticleMesh_119.geometry} material={materials.snowfleck} position={[-30.11, -7.43, 20.02]} rotation={[0.43, -0.16, -1.28]} />
          <mesh name="BakedParticleMesh_120" geometry={nodes.BakedParticleMesh_120.geometry} material={materials.snowfleck} position={[10.89, 12.26, 38.9]} rotation={[-0.38, 0.21, 1.66]} />
          <mesh name="BakedParticleMesh_121" geometry={nodes.BakedParticleMesh_121.geometry} material={materials.snowfleck} position={[21.62, -15.73, -2.6]} rotation={[2.2, -0.82, 2.57]} />
          <mesh name="BakedParticleMesh_122" geometry={nodes.BakedParticleMesh_122.geometry} material={materials.snowfleck} position={[-22.31, -18.49, 5.85]} rotation={[-2.09, -0.79, -3.06]} />
          <mesh name="BakedParticleMesh_123" geometry={nodes.BakedParticleMesh_123.geometry} material={materials.snowfleck} position={[-20.14, -0.42, 24.2]} rotation={[-2.96, -0.16, 2.93]} />
          <mesh name="BakedParticleMesh_124" geometry={nodes.BakedParticleMesh_124.geometry} material={materials.snowfleck} position={[17.78, -14.21, -9.73]} rotation={[1.2, 1.25, -0.3]} />
          <mesh name="BakedParticleMesh_125" geometry={nodes.BakedParticleMesh_125.geometry} material={materials.snowfleck} position={[-10.49, -5.74, 31.25]} rotation={[-1.26, -0.79, 0.08]} />
          <mesh name="BakedParticleMesh_126" geometry={nodes.BakedParticleMesh_126.geometry} material={materials.snowfleck} position={[9.42, 35.04, -7.8]} rotation={[1.05, 0.84, 2.99]} />
          <mesh name="BakedParticleMesh_127" geometry={nodes.BakedParticleMesh_127.geometry} material={materials.snowfleck} position={[-10.9, -5.98, 6.82]} rotation={[-2.18, -0.04, -0.56]} />
          <mesh name="BakedParticleMesh_128" geometry={nodes.BakedParticleMesh_128.geometry} material={materials.snowfleck} position={[-22.94, -19.19, -14.88]} rotation={[-1.69, 0.33, 1.45]} />
          <mesh name="BakedParticleMesh_129" geometry={nodes.BakedParticleMesh_129.geometry} material={materials.snowfleck} position={[-38.46, -0.46, -12.22]} rotation={[-2.35, -0.61, 1.54]} />
          <mesh name="BakedParticleMesh_130" geometry={nodes.BakedParticleMesh_130.geometry} material={materials.snowfleck} position={[-19.37, -19.18, -2.18]} rotation={[-3.06, 1.4, -1.32]} />
          <mesh name="BakedParticleMesh_131" geometry={nodes.BakedParticleMesh_131.geometry} material={materials.snowfleck} position={[27.88, -2.01, 6.57]} rotation={[-0.5, -0.48, -0.41]} />
          <mesh name="BakedParticleMesh_132" geometry={nodes.BakedParticleMesh_132.geometry} material={materials.snowfleck} position={[-33.88, -19.18, 12.89]} rotation={[-0.7, 0.1, -1.76]} />
          <mesh name="BakedParticleMesh_133" geometry={nodes.BakedParticleMesh_133.geometry} material={materials.snowfleck} position={[-15.69, 18.41, 5.27]} rotation={[0.78, 0.31, -3.13]} />
          <mesh name="BakedParticleMesh_134" geometry={nodes.BakedParticleMesh_134.geometry} material={materials.snowfleck} position={[4.35, 30.93, 20.32]} rotation={[-0.18, 1.05, 1.66]} />
          <mesh name="BakedParticleMesh_135" geometry={nodes.BakedParticleMesh_135.geometry} material={materials.snowfleck} position={[-14.47, 26.36, -9.09]} rotation={[0.91, -0.79, -1.06]} />
          <mesh name="BakedParticleMesh_136" geometry={nodes.BakedParticleMesh_136.geometry} material={materials.snowfleck} position={[10.21, 13.49, 19.36]} rotation={[3.02, 1.28, 2.58]} />
          <mesh name="BakedParticleMesh_137" geometry={nodes.BakedParticleMesh_137.geometry} material={materials.snowfleck} position={[-3.09, -0.48, -41.24]} rotation={[-1.02, 1.13, 2.16]} />
          <mesh name="BakedParticleMesh_138" geometry={nodes.BakedParticleMesh_138.geometry} material={materials.snowfleck} position={[-16.89, -12.29, -17.89]} rotation={[-1.01, 1.07, -1.93]} />
          <mesh name="BakedParticleMesh_139" geometry={nodes.BakedParticleMesh_139.geometry} material={materials.snowfleck} position={[25.77, -4.56, 31.04]} rotation={[0.23, -0.14, -1.79]} />
          <mesh name="BakedParticleMesh_140" geometry={nodes.BakedParticleMesh_140.geometry} material={materials.snowfleck} position={[21.91, -15.09, 1.64]} rotation={[1.52, 0.2, 1.11]} />
          <mesh name="BakedParticleMesh_141" geometry={nodes.BakedParticleMesh_141.geometry} material={materials.snowfleck} position={[-12.27, 22.52, 10.56]} rotation={[-1.74, -0.43, -2.05]} />
          <mesh name="BakedParticleMesh_142" geometry={nodes.BakedParticleMesh_142.geometry} material={materials.snowfleck} position={[7.44, -17.48, 5.86]} rotation={[0.4, -0.44, 1.32]} />
          <mesh name="BakedParticleMesh_143" geometry={nodes.BakedParticleMesh_143.geometry} material={materials.snowfleck} position={[-6.31, -19.16, 26.06]} rotation={[-0.31, 0.46, -1.49]} />
          <mesh name="BakedParticleMesh_144" geometry={nodes.BakedParticleMesh_144.geometry} material={materials.snowfleck} position={[13.71, 28.35, -7.14]} rotation={[-0.09, -0.64, 2.26]} />
          <mesh name="BakedParticleMesh_145" geometry={nodes.BakedParticleMesh_145.geometry} material={materials.snowfleck} position={[0.81, -4.02, -13.33]} rotation={[2.8, 0.29, 2.1]} />
          <mesh name="BakedParticleMesh_146" geometry={nodes.BakedParticleMesh_146.geometry} material={materials.snowfleck} position={[21.47, 30.02, 6.43]} rotation={[-1.87, -0.11, 2.78]} />
          <mesh name="BakedParticleMesh_147" geometry={nodes.BakedParticleMesh_147.geometry} material={materials.snowfleck} position={[-1.76, -14.45, -16.9]} rotation={[0.1, 0.14, -2.28]} />
          <mesh name="BakedParticleMesh_148" geometry={nodes.BakedParticleMesh_148.geometry} material={materials.snowfleck} position={[-2.7, -1.61, 23.37]} rotation={[-1.99, 1.11, -0.14]} />
          <mesh name="BakedParticleMesh_149" geometry={nodes.BakedParticleMesh_149.geometry} material={materials.snowfleck} position={[-22.17, 26.72, 9.57]} rotation={[2.03, -0.41, 1.84]} />
          <mesh name="BakedParticleMesh_150" geometry={nodes.BakedParticleMesh_150.geometry} material={materials.snowfleck} position={[-12.15, 30.81, -6]} rotation={[-1.95, 1.19, -2.98]} />
          <mesh name="BakedParticleMesh_151" geometry={nodes.BakedParticleMesh_151.geometry} material={materials.snowfleck} position={[-22.69, -6.73, 10.97]} rotation={[-1.39, 0.37, -2.36]} />
          <mesh name="BakedParticleMesh_152" geometry={nodes.BakedParticleMesh_152.geometry} material={materials.snowfleck} position={[5.5, 12.82, -20.1]} rotation={[1.07, -0.1, -2.36]} />
          <mesh name="BakedParticleMesh_153" geometry={nodes.BakedParticleMesh_153.geometry} material={materials.snowfleck} position={[13.39, 11.15, -3.05]} rotation={[0.08, 0.48, 2.65]} />
          <mesh name="BakedParticleMesh_154" geometry={nodes.BakedParticleMesh_154.geometry} material={materials.snowfleck} position={[20.74, 14.15, -23.41]} rotation={[-2.65, 0.86, -0.63]} />
          <mesh name="BakedParticleMesh_155" geometry={nodes.BakedParticleMesh_155.geometry} material={materials.snowfleck} position={[13.1, -10.09, -1.38]} rotation={[-2.09, -0.47, 2.44]} />
          <mesh name="BakedParticleMesh_156" geometry={nodes.BakedParticleMesh_156.geometry} material={materials.snowfleck} position={[10.7, -16.96, -3.54]} rotation={[-2.33, -1.14, 2.17]} />
          <mesh name="BakedParticleMesh_157" geometry={nodes.BakedParticleMesh_157.geometry} material={materials.snowfleck} position={[12.02, 19.79, 13.57]} rotation={[1.39, 0.45, -1.16]} />
          <mesh name="BakedParticleMesh_158" geometry={nodes.BakedParticleMesh_158.geometry} material={materials.snowfleck} position={[-32.68, 11.45, 16.88]} rotation={[0.07, -0.14, 0.05]} />
          <mesh name="BakedParticleMesh_159" geometry={nodes.BakedParticleMesh_159.geometry} material={materials.snowfleck} position={[32.61, 9.18, 19.52]} rotation={[-0.29, -0.22, -1.95]} />
          <mesh name="BakedParticleMesh_160" geometry={nodes.BakedParticleMesh_160.geometry} material={materials.snowfleck} position={[13.79, 9.36, 5.53]} rotation={[0.17, 0.14, 2.13]} />
          <mesh name="BakedParticleMesh_161" geometry={nodes.BakedParticleMesh_161.geometry} material={materials.snowfleck} position={[1.57, 31.47, -16.77]} rotation={[0.1, 0.44, -2.9]} />
          <mesh name="BakedParticleMesh_162" geometry={nodes.BakedParticleMesh_162.geometry} material={materials.snowfleck} position={[-3.89, 1.1, -33.05]} rotation={[2.22, -0.39, 0.66]} />
          <mesh name="BakedParticleMesh_163" geometry={nodes.BakedParticleMesh_163.geometry} material={materials.snowfleck} position={[18.98, 14.35, -12.82]} rotation={[1.34, -0.59, 0.73]} />
          <mesh name="BakedParticleMesh_164" geometry={nodes.BakedParticleMesh_164.geometry} material={materials.snowfleck} position={[-26.33, -0.4, 34.15]} rotation={[0.31, 0.75, -1.28]} />
          <mesh name="BakedParticleMesh_165" geometry={nodes.BakedParticleMesh_165.geometry} material={materials.snowfleck} position={[18.76, 19.12, -17.34]} rotation={[1.52, -0.53, -0.31]} />
          <mesh name="BakedParticleMesh_166" geometry={nodes.BakedParticleMesh_166.geometry} material={materials.snowfleck} position={[30.03, -9.97, 6.57]} rotation={[-0.99, 0.46, -1.45]} />
          <mesh name="BakedParticleMesh_167" geometry={nodes.BakedParticleMesh_167.geometry} material={materials.snowfleck} position={[4.27, 21.18, -6.68]} rotation={[0.44, 0.37, -1.73]} />
          <mesh name="BakedParticleMesh_168" geometry={nodes.BakedParticleMesh_168.geometry} material={materials.snowfleck} position={[-24.11, -7.71, -11.96]} rotation={[-1.59, -0.34, -1.13]} />
          <mesh name="BakedParticleMesh_169" geometry={nodes.BakedParticleMesh_169.geometry} material={materials.snowfleck} position={[-20.42, -1.51, -17.46]} rotation={[-0.24, -1.28, -0.99]} />
          <mesh name="BakedParticleMesh_170" geometry={nodes.BakedParticleMesh_170.geometry} material={materials.snowfleck} position={[30.8, 18.53, -1.95]} rotation={[-2.28, -0.8, 1.99]} />
          <mesh name="BakedParticleMesh_171" geometry={nodes.BakedParticleMesh_171.geometry} material={materials.snowfleck} position={[-24.99, -19.18, -3.51]} rotation={[1.62, 0.65, -2.17]} />
          <mesh name="BakedParticleMesh_172" geometry={nodes.BakedParticleMesh_172.geometry} material={materials.snowfleck} position={[1.83, 21.37, 21.64]} rotation={[2.95, 0.83, -2.57]} />
          <mesh name="BakedParticleMesh_173" geometry={nodes.BakedParticleMesh_173.geometry} material={materials.snowfleck} position={[-19.83, -1.9, -16.35]} rotation={[-0.58, 1.16, -1.81]} />
          <mesh name="BakedParticleMesh_174" geometry={nodes.BakedParticleMesh_174.geometry} material={materials.snowfleck} position={[14.91, -13.44, 32.19]} rotation={[-0.45, -1.18, -1.9]} />
          <mesh name="BakedParticleMesh_175" geometry={nodes.BakedParticleMesh_175.geometry} material={materials.snowfleck} position={[18.09, 4.52, 4.7]} rotation={[0.21, -0.77, 2.44]} />
          <mesh name="BakedParticleMesh_176" geometry={nodes.BakedParticleMesh_176.geometry} material={materials.snowfleck} position={[8.51, -18.15, -11.39]} rotation={[-2.79, -0.46, 1.52]} />
          <mesh name="BakedParticleMesh_177" geometry={nodes.BakedParticleMesh_177.geometry} material={materials.snowfleck} position={[-19.15, -6.62, -34.5]} rotation={[0.72, 0.79, -0.9]} />
          <mesh name="BakedParticleMesh_178" geometry={nodes.BakedParticleMesh_178.geometry} material={materials.snowfleck} position={[22.65, 4.44, 27.08]} rotation={[0.8, 1.04, -2.91]} />
          <mesh name="BakedParticleMesh_179" geometry={nodes.BakedParticleMesh_179.geometry} material={materials.snowfleck} position={[-5.16, 25.91, 12.46]} rotation={[2.28, 0.07, 2.8]} />
          <mesh name="BakedParticleMesh_180" geometry={nodes.BakedParticleMesh_180.geometry} material={materials.snowfleck} position={[32.88, -6.95, 10.12]} rotation={[-0.98, 1.44, -1.05]} />
          <mesh name="BakedParticleMesh_181" geometry={nodes.BakedParticleMesh_181.geometry} material={materials.snowfleck} position={[-18.64, 25.84, -19.71]} rotation={[-1.04, 0.38, -0.73]} />
          <mesh name="BakedParticleMesh_182" geometry={nodes.BakedParticleMesh_182.geometry} material={materials.snowfleck} position={[19.12, -16.91, -8.46]} rotation={[-2.38, 1.19, 0.76]} />
          <mesh name="BakedParticleMesh_183" geometry={nodes.BakedParticleMesh_183.geometry} material={materials.snowfleck} position={[5.99, 29.33, -16.65]} rotation={[-1.88, 0.4, 2.68]} />
          <mesh name="BakedParticleMesh_184" geometry={nodes.BakedParticleMesh_184.geometry} material={materials.snowfleck} position={[25.34, 10.91, 12.87]} rotation={[0.47, -0.46, -1.27]} />
          <mesh name="BakedParticleMesh_185" geometry={nodes.BakedParticleMesh_185.geometry} material={materials.snowfleck} position={[-5.34, -9.19, 14.81]} rotation={[-3.03, 0.04, 1.06]} />
          <mesh name="BakedParticleMesh_186" geometry={nodes.BakedParticleMesh_186.geometry} material={materials.snowfleck} position={[-10.63, -6.33, 29.78]} rotation={[1.36, 0.3, 2.56]} />
          <mesh name="BakedParticleMesh_187" geometry={nodes.BakedParticleMesh_187.geometry} material={materials.snowfleck} position={[5.24, -18.67, -4.66]} rotation={[1.94, -0.75, 3.01]} />
          <mesh name="BakedParticleMesh_188" geometry={nodes.BakedParticleMesh_188.geometry} material={materials.snowfleck} position={[25.66, -7.43, -18]} rotation={[2.15, -1.26, 2.73]} />
          <mesh name="BakedParticleMesh_189" geometry={nodes.BakedParticleMesh_189.geometry} material={materials.snowfleck} position={[15.46, -18.11, -9.36]} rotation={[-3.09, 0.42, 0.93]} />
          <mesh name="BakedParticleMesh_190" geometry={nodes.BakedParticleMesh_190.geometry} material={materials.snowfleck} position={[22.91, -6.4, -2.18]} rotation={[-0.14, -1.34, -2.72]} />
          <mesh name="BakedParticleMesh_191" geometry={nodes.BakedParticleMesh_191.geometry} material={materials.snowfleck} position={[-20.67, 35.61, 0.44]} rotation={[-2.31, -1, -0.37]} />
          <mesh name="BakedParticleMesh_192" geometry={nodes.BakedParticleMesh_192.geometry} material={materials.snowfleck} position={[-2.69, 25.16, 13.64]} rotation={[0.53, 1.42, 0.17]} />
          <mesh name="BakedParticleMesh_193" geometry={nodes.BakedParticleMesh_193.geometry} material={materials.snowfleck} position={[-28.26, 29.07, 5.52]} rotation={[-2.55, 0.22, -0.3]} />
          <mesh name="BakedParticleMesh_194" geometry={nodes.BakedParticleMesh_194.geometry} material={materials.snowfleck} position={[-18.02, 6.97, -2.63]} rotation={[-0.96, 0.49, -1.96]} />
          <mesh name="BakedParticleMesh_195" geometry={nodes.BakedParticleMesh_195.geometry} material={materials.snowfleck} position={[14.6, -18.68, -26.51]} rotation={[-2.73, -0.74, 0.14]} />
          <mesh name="BakedParticleMesh_196" geometry={nodes.BakedParticleMesh_196.geometry} material={materials.snowfleck} position={[39.03, -6.24, -2.79]} rotation={[2.37, 1.29, 2.55]} />
          <mesh name="BakedParticleMesh_197" geometry={nodes.BakedParticleMesh_197.geometry} material={materials.snowfleck} position={[35.27, 7.03, 6.79]} rotation={[2.34, -0.2, 1.2]} />
          <mesh name="BakedParticleMesh_198" geometry={nodes.BakedParticleMesh_198.geometry} material={materials.snowfleck} position={[13.48, 17.86, -2.26]} rotation={[0.96, -0.77, -0.76]} />
          <mesh name="BakedParticleMesh_199" geometry={nodes.BakedParticleMesh_199.geometry} material={materials.snowfleck} position={[-0.87, -12.95, -26.81]} rotation={[1.67, 0.5, 0.63]} />
          <mesh name="BakedParticleMesh_200" geometry={nodes.BakedParticleMesh_200.geometry} material={materials.snowfleck} position={[31.99, -18.55, -16.17]} rotation={[2, -0.91, 1.04]} />
          <mesh name="BakedParticleMesh_201" geometry={nodes.BakedParticleMesh_201.geometry} material={materials.snowfleck} position={[1.1, 38.21, -9.14]} rotation={[2.21, -0.7, -1.57]} />
          <mesh name="BakedParticleMesh_202" geometry={nodes.BakedParticleMesh_202.geometry} material={materials.snowfleck} position={[42.42, 5.45, -8.19]} rotation={[2.47, -1.02, 1.76]} />
          <mesh name="BakedParticleMesh_203" geometry={nodes.BakedParticleMesh_203.geometry} material={materials.snowfleck} position={[-7.86, 29.43, -21.93]} rotation={[-0.13, 0.15, -2.93]} />
          <mesh name="BakedParticleMesh_204" geometry={nodes.BakedParticleMesh_204.geometry} material={materials.snowfleck} position={[20.9, -0.33, 27.84]} rotation={[0.13, -0.63, 2.67]} />
          <mesh name="BakedParticleMesh_205" geometry={nodes.BakedParticleMesh_205.geometry} material={materials.snowfleck} position={[21.34, 9.89, 36.17]} rotation={[-2.33, 0.64, 1.9]} />
          <mesh name="BakedParticleMesh_206" geometry={nodes.BakedParticleMesh_206.geometry} material={materials.snowfleck} position={[-19.49, -18.43, 26.14]} rotation={[0.78, 0.51, -2.15]} />
          <mesh name="BakedParticleMesh_207" geometry={nodes.BakedParticleMesh_207.geometry} material={materials.snowfleck} position={[17.43, -18.66, 18.61]} rotation={[1.51, 0.55, 0.21]} />
          <mesh name="BakedParticleMesh_208" geometry={nodes.BakedParticleMesh_208.geometry} material={materials.snowfleck} position={[36.36, -16.85, 11.71]} rotation={[1.63, 0.32, 1.19]} />
          <mesh name="BakedParticleMesh_209" geometry={nodes.BakedParticleMesh_209.geometry} material={materials.snowfleck} position={[-1.47, -8.89, 30.57]} rotation={[-1.56, -0.22, -0.74]} />
          <mesh name="BakedParticleMesh_210" geometry={nodes.BakedParticleMesh_210.geometry} material={materials.snowfleck} position={[-17.45, 15.69, -18.68]} rotation={[-2.2, -0.77, -0.5]} />
          <mesh name="BakedParticleMesh_211" geometry={nodes.BakedParticleMesh_211.geometry} material={materials.snowfleck} position={[-37.3, 22.49, 3]} rotation={[-1.29, 0.34, 0.92]} />
          <mesh name="BakedParticleMesh_212" geometry={nodes.BakedParticleMesh_212.geometry} material={materials.snowfleck} position={[-2.49, -11.13, -1.4]} rotation={[1.67, 0.16, -0.16]} />
          <mesh name="BakedParticleMesh_213" geometry={nodes.BakedParticleMesh_213.geometry} material={materials.snowfleck} position={[-22.75, -17.57, -35.73]} rotation={[-2, 0.25, -0.93]} />
          <mesh name="BakedParticleMesh_214" geometry={nodes.BakedParticleMesh_214.geometry} material={materials.snowfleck} position={[-29.01, 6.18, -15.5]} rotation={[1.64, -0.26, 1.01]} />
          <mesh name="BakedParticleMesh_215" geometry={nodes.BakedParticleMesh_215.geometry} material={materials.snowfleck} position={[-37.39, 0.86, -27.05]} rotation={[2.75, -0.46, -1.03]} />
          <mesh name="BakedParticleMesh_216" geometry={nodes.BakedParticleMesh_216.geometry} material={materials.snowfleck} position={[-25.12, -16.65, -19.61]} rotation={[-2.44, 0.6, 1.75]} />
          <mesh name="BakedParticleMesh_217" geometry={nodes.BakedParticleMesh_217.geometry} material={materials.snowfleck} position={[-7.88, 23.85, -17.32]} rotation={[1.7, -0.81, -0.78]} />
          <mesh name="BakedParticleMesh_218" geometry={nodes.BakedParticleMesh_218.geometry} material={materials.snowfleck} position={[-0.21, 29.24, -29.92]} rotation={[-2.83, 0.01, -1.93]} />
          <mesh name="BakedParticleMesh_219" geometry={nodes.BakedParticleMesh_219.geometry} material={materials.snowfleck} position={[-31.37, -7.26, 7.53]} rotation={[3.08, 0.01, -1.45]} />
          <mesh name="BakedParticleMesh_220" geometry={nodes.BakedParticleMesh_220.geometry} material={materials.snowfleck} position={[-28.45, -18.99, 31.39]} rotation={[-3.01, -0.62, 1.28]} />
          <mesh name="BakedParticleMesh_221" geometry={nodes.BakedParticleMesh_221.geometry} material={materials.snowfleck} position={[35.96, -17.12, -16.29]} rotation={[1.64, -0.42, -0.54]} />
          <mesh name="BakedParticleMesh_222" geometry={nodes.BakedParticleMesh_222.geometry} material={materials.snowfleck} position={[-21.4, -15.38, -11.59]} rotation={[-1.24, 0.53, 2.5]} />
          <mesh name="BakedParticleMesh_223" geometry={nodes.BakedParticleMesh_223.geometry} material={materials.snowfleck} position={[-15.94, -9.64, -42.27]} rotation={[1.24, 1.26, 0.72]} />
          <mesh name="BakedParticleMesh_224" geometry={nodes.BakedParticleMesh_224.geometry} material={materials.snowfleck} position={[-22.33, -17.35, -9.43]} rotation={[-1.4, -0.04, -2.37]} />
          <mesh name="BakedParticleMesh_225" geometry={nodes.BakedParticleMesh_225.geometry} material={materials.snowfleck} position={[-29.82, 9.05, 14.57]} rotation={[1.2, 0.25, -0.18]} />
          <mesh name="BakedParticleMesh_226" geometry={nodes.BakedParticleMesh_226.geometry} material={materials.snowfleck} position={[21.91, -15.07, 32.96]} rotation={[-2.62, -0.73, -1.97]} />
          <mesh name="BakedParticleMesh_227" geometry={nodes.BakedParticleMesh_227.geometry} material={materials.snowfleck} position={[36.92, -0.9, -20.39]} rotation={[-3.09, 0.93, -1.79]} />
          <mesh name="BakedParticleMesh_228" geometry={nodes.BakedParticleMesh_228.geometry} material={materials.snowfleck} position={[16.91, -19.12, 17.85]} rotation={[0.29, 0.2, 0.56]} />
          <mesh name="BakedParticleMesh_229" geometry={nodes.BakedParticleMesh_229.geometry} material={materials.snowfleck} position={[18.39, -14.66, 5.21]} rotation={[1.91, 1.18, 1.41]} />
          <mesh name="BakedParticleMesh_230" geometry={nodes.BakedParticleMesh_230.geometry} material={materials.snowfleck} position={[-12.57, 24.42, 31.62]} rotation={[0.64, -0.74, -2.42]} />
          <mesh name="BakedParticleMesh_231" geometry={nodes.BakedParticleMesh_231.geometry} material={materials.snowfleck} position={[-30.04, 21.95, -7.02]} rotation={[2.67, -0.7, 0.2]} />
          <mesh name="BakedParticleMesh_232" geometry={nodes.BakedParticleMesh_232.geometry} material={materials.snowfleck} position={[10.27, 5.89, 36.43]} rotation={[-2.89, -1.08, -0.61]} />
          <mesh name="BakedParticleMesh_233" geometry={nodes.BakedParticleMesh_233.geometry} material={materials.snowfleck} position={[-5.04, -17.79, 3.28]} rotation={[-1.05, 0.02, 2.76]} />
          <mesh name="BakedParticleMesh_234" geometry={nodes.BakedParticleMesh_234.geometry} material={materials.snowfleck} position={[-29.27, 11.61, -14.32]} rotation={[-2.21, -0.5, -0.25]} />
          <mesh name="BakedParticleMesh_235" geometry={nodes.BakedParticleMesh_235.geometry} material={materials.snowfleck} position={[26.68, 8.8, -31.61]} rotation={[2.98, 1.05, 0.43]} />
          <mesh name="BakedParticleMesh_236" geometry={nodes.BakedParticleMesh_236.geometry} material={materials.snowfleck} position={[35.51, -9.3, -2.9]} rotation={[1.82, -0.94, 0.06]} />
          <mesh name="BakedParticleMesh_237" geometry={nodes.BakedParticleMesh_237.geometry} material={materials.snowfleck} position={[17.99, 9, -39.67]} rotation={[1.74, -0.97, -2.4]} />
          <mesh name="BakedParticleMesh_238" geometry={nodes.BakedParticleMesh_238.geometry} material={materials.snowfleck} position={[0.06, 24.05, -27.63]} rotation={[-0.17, 1.19, -1.04]} />
          <mesh name="BakedParticleMesh_239" geometry={nodes.BakedParticleMesh_239.geometry} material={materials.snowfleck} position={[36.75, -9.14, -6.32]} rotation={[2.96, -0.73, 2.81]} />
          <mesh name="BakedParticleMesh_240" geometry={nodes.BakedParticleMesh_240.geometry} material={materials.snowfleck} position={[-37.95, -17.75, -24.2]} rotation={[-1.53, -0.59, -2.39]} />
          <mesh name="BakedParticleMesh_241" geometry={nodes.BakedParticleMesh_241.geometry} material={materials.snowfleck} position={[23.03, -9.42, 33.03]} rotation={[1.45, -0.86, 1.58]} />
          <mesh name="BakedParticleMesh_242" geometry={nodes.BakedParticleMesh_242.geometry} material={materials.snowfleck} position={[23.87, -13.75, 8.45]} rotation={[2.79, 0.91, 3.05]} />
          <mesh name="BakedParticleMesh_243" geometry={nodes.BakedParticleMesh_243.geometry} material={materials.snowfleck} position={[-21.19, 24.33, 26.07]} rotation={[1.29, 0.51, 2.27]} />
          <mesh name="BakedParticleMesh_244" geometry={nodes.BakedParticleMesh_244.geometry} material={materials.snowfleck} position={[1.63, -19.03, -3.46]} rotation={[3.08, -0.96, -1.35]} />
          <mesh name="BakedParticleMesh_245" geometry={nodes.BakedParticleMesh_245.geometry} material={materials.snowfleck} position={[-19.89, 13.19, 33.06]} rotation={[2.26, 0.1, 0.04]} />
          <mesh name="BakedParticleMesh_246" geometry={nodes.BakedParticleMesh_246.geometry} material={materials.snowfleck} position={[2.68, 23.12, -33.67]} rotation={[-1.25, -0.86, -2.01]} />
          <mesh name="BakedParticleMesh_247" geometry={nodes.BakedParticleMesh_247.geometry} material={materials.snowfleck} position={[-1.91, 27.46, -32.55]} rotation={[-2.43, -0.13, 0.29]} />
          <mesh name="BakedParticleMesh_248" geometry={nodes.BakedParticleMesh_248.geometry} material={materials.snowfleck} position={[19.77, -13.9, 30.72]} rotation={[0.87, -0.02, 1.93]} />
          <mesh name="BakedParticleMesh_249" geometry={nodes.BakedParticleMesh_249.geometry} material={materials.snowfleck} position={[-14.34, -18.9, -39.47]} rotation={[-2.55, -0.72, -1.37]} />
          <mesh name="BakedParticleMesh_250" geometry={nodes.BakedParticleMesh_250.geometry} material={materials.snowfleck} position={[15.28, 10.54, 38.58]} rotation={[1.85, 1.04, 0.36]} />
          <mesh name="BakedParticleMesh_251" geometry={nodes.BakedParticleMesh_251.geometry} material={materials.snowfleck} position={[-13.54, -17.54, 39.52]} rotation={[-2.32, -0.82, 2.79]} />
          <mesh name="BakedParticleMesh_252" geometry={nodes.BakedParticleMesh_252.geometry} material={materials.snowfleck} position={[-13.01, -5.94, -46.49]} rotation={[0.7, -0.76, 0.22]} />
          <mesh name="BakedParticleMesh_253" geometry={nodes.BakedParticleMesh_253.geometry} material={materials.snowfleck} position={[-15.87, -8.51, 40.92]} rotation={[1.44, 1.3, 1.41]} />
          <mesh name="BakedParticleMesh_254" geometry={nodes.BakedParticleMesh_254.geometry} material={materials.snowfleck} position={[24.73, 20.5, 23.2]} rotation={[-1.86, 0.67, -2.12]} />
          <mesh name="BakedParticleMesh_255" geometry={nodes.BakedParticleMesh_255.geometry} material={materials.snowfleck} position={[-23.06, 20.04, 29.51]} rotation={[1.51, -0.36, -0.58]} />
          <mesh name="BakedParticleMesh_256" geometry={nodes.BakedParticleMesh_256.geometry} material={materials.snowfleck} position={[-44.9, -9.09, 2.66]} rotation={[0.14, 1.16, 0.44]} />
          <mesh name="BakedParticleMesh_257" geometry={nodes.BakedParticleMesh_257.geometry} material={materials.snowfleck} position={[-9.32, 2.03, 42.39]} rotation={[-0.34, 1.01, 2.34]} />
          <mesh name="BakedParticleMesh_258" geometry={nodes.BakedParticleMesh_258.geometry} material={materials.snowfleck} position={[13.61, 34.09, -17.03]} rotation={[2.16, 0.97, -1.35]} />
          <mesh name="BakedParticleMesh_259" geometry={nodes.BakedParticleMesh_259.geometry} material={materials.snowfleck} position={[16.1, 33.65, -19.76]} rotation={[1.33, 0.76, 2.81]} />
          <mesh name="BakedParticleMesh_260" geometry={nodes.BakedParticleMesh_260.geometry} material={materials.snowfleck} position={[1.61, 3.72, -45.76]} rotation={[-2.95, -0.13, -0.01]} />
          <mesh name="BakedParticleMesh_261" geometry={nodes.BakedParticleMesh_261.geometry} material={materials.snowfleck} position={[10.76, 36.78, -14.52]} rotation={[-1, 0.72, 2.01]} />
          <mesh name="BakedParticleMesh_262" geometry={nodes.BakedParticleMesh_262.geometry} material={materials.snowfleck} position={[-3.41, 35.41, 11.11]} rotation={[2.07, -0.36, 3.09]} />
          <mesh name="BakedParticleMesh_263" geometry={nodes.BakedParticleMesh_263.geometry} material={materials.snowfleck} position={[-28.16, 20.84, 21.96]} rotation={[-2.2, -0.8, -0.72]} />
          <mesh name="BakedParticleMesh_264" geometry={nodes.BakedParticleMesh_264.geometry} material={materials.snowfleck} position={[-12.94, 3.2, 39.64]} rotation={[0, 0.27, 3.03]} />
          <mesh name="BakedParticleMesh_265" geometry={nodes.BakedParticleMesh_265.geometry} material={materials.snowfleck} position={[31.36, -12.99, -33.46]} rotation={[-0.07, 0.82, -1.22]} />
          <mesh name="BakedParticleMesh_266" geometry={nodes.BakedParticleMesh_266.geometry} material={materials.snowfleck} position={[20.03, -18.18, 34.24]} rotation={[-0.52, 0.55, -0.54]} />
          <mesh name="glass" geometry={nodes.glass.geometry}position={[-0.61, -5.65, -1.77]} rotation={[-Math.PI / 2, 0, 0]} >
            <meshPhysicalMaterial {...Glass}></meshPhysicalMaterial>
          </mesh>
          <mesh name="outer-sphere-ground" geometry={nodes['outer-sphere-ground'].geometry} material={materials['22 - Default']} position={[-0.11, -24.17, -1.59]} rotation={[-Math.PI / 2, 0, 0]} />
          {/* <mesh name="snow-deflect" geometry={nodes['snow-deflect'].geometry} material={materials.deer4_mat} position={[-0.61, -5.65, -1.77]} rotation={[-Math.PI / 2, 0, 0]} scale={0.93} /> */}
          {/* <mesh name="snowfleck" geometry={nodes.snowfleck.geometry} material={materials.snowfleck} position={[58.95, -24.99, -2.38]} rotation={[-Math.PI / 2, 0, 0]} /> */}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/SnowGlobe.glb')
