/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Snowman_01(props) {
  const { nodes, materials } = useGLTF('/Snowman/Snowman_01.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Snowman.geometry} material={materials['Mat.1']} />
    </group>
  )
}

useGLTF.preload('/Snowman/Snowman_01.glb')
export default Snowman_01
