/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Snowman_08(props) {
  const { nodes, materials } = useGLTF('/Snowman/Snowman_08.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Snowman_1.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/Snowman/Snowman_08.glb')
export default Snowman_08
