server:
  servlet:
    context-path: /api

spring:
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

  # swagger 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
      #로컬 환경
    url: jdbc:mysql://localhost:3306/snowball?useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    username: ssafy
    password: ssafy

    # ec2 DB에 연결
#    url: jdbc:mysql://k7a601.p.ssafy.io:3306/snowball?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
#    username: ssafy
#    password: mylittlesnowball601!


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500
        #        show_sql: false
        format_sql: true
        show_sql: true

    open-in-view: false

  data:
    mongodb:

      # ec2 server setting
      username: ssafy
      password: mylittlesnowball601!
      host: k7a601.p.ssafy.io
      port: 27017
      database: snowball
      authentication-database: admin
#     uri: mongodb://ssafy:mylittlesnowball601!@k7a601.p.ssafy.io:27017/snowball

      # local setting
#      uri: mongodb://localhost:27017/snowball

    web:
      pageable:
        default-per-size: 20
        max-page-size: 2000

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 272ae474b08df0caa648c29a2cf58ff2
            client-secret: PE7rGTcwahIX2yHK8ZgYHDnLT6BMUHP3
            redirect-uri: https://mylittlesnowball.com/api/login/oauth2/code/kakao
#            redirect-uri: http://localhost:8080/api/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  task:
    scheduling:
      pool:
        size: 10

token:
  # 일단 하루
  expiration_time: 86400000
  secret: secretcode
  refresh-cookie-key: refresh

oauth2:
  # 클라이언트 주소
    authorizedRedirectUri: https://mylittlesnowball.com
#    authorizedRedirectUri: http://localhost:3000/code/callback
#  authorizedRedirectUri: https://j7a603.p.ssafy.io/oauth2/redirect

cloud:
  aws:
    credentials:
      accessKey: AKIA3FTVN73LLSOXAIHF
      secretKey: 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
    s3:
      bucket: 601snowball
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: debug
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: debug

kakao:
  restapikey:
